apiVersion: apps/v1
kind: Deployment
metadata:
  name: xeropark-api
  namespace: xeropark-api
spec:
  selector:
    matchLabels:
      app: xeropark-api
  replicas: 4 # podの数
  template:
    metadata:
      labels:
        app: xeropark-api
    spec:
      containers:
      - name: xeropark-api
        image: python:3.11.10-bookworm
        ports:
        - containerPort: 6789