apiVersion: v1
kind: Service
metadata:
  name: xeropark-api
  namespace: xeropark-api
spec:
  selector:
    app: xeropark-api
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 6789
    nodePort: 30001
  type: NodePort
  selector:
    app: xeropark-api