apiVersion: v1
kind: Service
metadata:
  name: xeropark-api
  namespace: xeropark-api
spec:
  selector:
    app: xeropark-api
  ports:
  - protocol: TCP
    post: 80
    targetPort: 6789
  type: NodePort
  selector:
    app: xeropark-api